### ISSUE TITLE
Requirements for the GPU

### ISSUE THREAD

**Issue by YQisme** [TIGER-AI-Lab/AnyV2V#2]
The duration and resolution of the video, as well as the corresponding GPU RAM.

**Comment by vinesmsuic** [comment]
Hi, our framework works on the popular resolutions including square, landscape, and portrait. Due to current I2V model properties, it can edit 2 seconds video. For GPU, we run our experiments on a A6000.

**Comment by zerzhier** [comment]
can this framework works on a RTX3080 or a RTX3090 GPU？

**Comment by wren93** [comment]
Editing a 512x512 video takes ~11G GPU memory for i2vgen-xl using fp16. So this should work on a 3090 but may be a bit difficult for a 3080.
