### ISSUE TITLE
Adaptation for inpainting

### ISSUE THREAD

**Issue by alasokolova** [TIGER-AI-Lab/AnyV2V#4]
Hey,
Can AnyV2V be adapted for video inpainting task?

**Comment by wren93** [comment]
Hi, thanks for your interest. We haven't thoroughly tested the framework for video inpainting, but I guess the method generally makes sense for inpainting tasks such that given a masked video, you can first use some image inpainting method to generate the first inpainted frame and let the I2V model propagate the frame to the entire video. We do have some examples for object swapping which should also be related to inpainting.

**Comment by vinesmsuic** [comment]
We did try some tasks similar to inpainting (e.g. Adding objects and Removing objects) and found that such modifications are even better with such tasks compared to frame-based methods due to the inherent knowledge from I2V models.

**Comment by alasokolova** [comment]
Thanks for the answers!
@vinesmsuic did you try it the way @wren93 described? Applying image-based model to the first frame and then propagating to the whole video? I will try it :)

**Comment by vinesmsuic** [comment]
We tried using instructpix2pix to add/remove objects in the first frame. Of coz we were talking about the AnyV2V method.
