### ISSUE TITLE
anyv2v with instantid

### ISSUE THREAD

**Issue by akk-123** [TIGER-AI-Lab/AnyV2V#7]
how to run anyv2v with instantid?

**Comment by vinesmsuic** [comment]
Hi, 

Currently you can rely on our demo (locally or online) and InstantID's demo for the image output.

AnyV2V online Demo: https://huggingface.co/spaces/TIGER-Lab/AnyV2V
<img width="1197" alt="Screenshot 2024-04-09 at 2 00 41 PM" src="https://github.com/TIGER-AI-Lab/AnyV2V/assets/34955859/ddc05b91-0326-4050-8a8b-3e83d0a6804c">

In the Image Editing Stage, you can download the first frame and go to the [InstantID online Demo](https://huggingface.co/spaces/InstantX/InstantID) to process the InstantID image. Then upload it to "The Edited Frame" and do not click on the "Edit the First Frame" button and move to the next stage directly.

Max
