### ISSUE TITLE
No module named 'diffusers.models.unets'

### ISSUE THREAD

**Issue by Aprilpl** [TIGER-AI-Lab/AnyV2V#9]
When I ran the command `python gradio_demo_style.py`, I encountered some environment issues. I have attempted to use different versions of diffusers, but none of them seem to resolve the problem. Could you please provide guidance on how to resolve this issue?

Below is the error traceback:

```
Traceback (most recent call last):
  File "/home/ubuntu/AnyV2V/gradio_demo_style.py", line 21, in <module>
    from pipelines.pipeline_i2vgen_xl import I2VGenXLPipeline
  File "/home/ubuntu/AnyV2V/i2vgen-xl/pipelines/pipeline_i2vgen_xl.py", line 29, in <module>
    from diffusers.models.unets.unet_i2vgen_xl import I2VGenXLUNet
ModuleNotFoundError: No module named 'diffusers.models.unets'
```

**Comment by vinesmsuic** [comment]
Hi, can you list your diffusers version?
```python
pip list | grep diffusers
```

**Comment by Aprilpl** [comment]
> Hi, can you list your diffusers version?
> 
> ```python
> pip list | grep diffusers
> ```

I am very happy to. This is my conda environment and the version of diffusers:
```
(anyv2v-i2vgen-xl) ubuntu@ip-172-xx-xx-x:~$ pip -V
pip 23.3.1 from /home/ubuntu/miniconda3/envs/anyv2v-i2vgen-xl/lib/python3.9/site-packages/pip (python 3.9)
(anyv2v-i2vgen-xl) ubuntu@ip-172-xx-xx-xx:~$ pip list | grep diffusers
diffusers                 0.26.3
```

**Comment by vinesmsuic** [comment]
Did you run the file from the root AnyV2V dir?

**Comment by Aprilpl** [comment]
> Did you run the file from the root AnyV2V dir?

Yes, of course.
